arch: vit_tiny
batch_size: 256
ckp_key: teacher
crop_size: 32  # 224
dataset: CIFAR10  # ImageNet
epochs: 100
img_size: 32
lars: false
lr: 30.0
momentum: 0.9
resize_size: 36  # 256
weight_decay: 0.0
patch_size: 4
pretrained: exp/checkpoint.pth
output_dir: exp
val_freq: 1
logger_freq: 50
dist_url: env://
dist_backend: gloo  # gloo
num_workers: 8
data_path: ../datasets/CIFAR10  # /data/datasets/ImageNet/imagenet-pytorch
n_last_blocks: 4
avgpool: False