arch: vit_small
avgpool: false
batch_size: 256
ckp_key: teacher
crop_size: 224
dataset: ImageNet
epochs: 100
img_size: 224
lars: false
lr: 0.001
momentum: 0.9
n_last_blocks: 4
patch_size: 16
pretrained: checkpoint.pth
resize_size: 256
weight_decay: 0.0