arch: resnet50
avgpool: false
batch_size: 128
crop_size: 224
dataset: ImageNet
#epochs: 100
img_size: 224
#lr: 0.001
#momentum: 0.9
n_last_blocks: 4
#optimizer: sgd
patch_size: 16
resize_size: 256
#weight_decay: 0.0
# misc
ckp_key: model
data_path: null
dist_backend: nccl
dist_url: env://
num_workers: 10
output_dir: .
pretrained: checkpoint.pth
#val_freq: 1
load_features: false
use_cuda: false
nb_knn:
- 10
- 20
- 100
- 200
temperature: 0.07