batch_size: 4096
ckp_key: model
crop_size: 224
img_size: 224
dataset: ImageNet
epochs: 90
lr: 0.1
momentum: 0.9
resize_size: 256
weight_decay: 0.0
patch_size: 16
n_last_blocks: 4
avgpool: false
finetune: false
optimizer: lars
logger_freq: 50