arch: vit_small
avgpool: false
batch_size: 1024
crop_size: 224
dataset: ImageNet
epochs: 100
img_size: 224
lr: 0.001
momentum: 0.9
n_last_blocks: 4
optimizer: sgd
patch_size: 16
resize_size: 256
weight_decay: 0.0
# misc
ckp_key: teacher
data_path: null
dist_backend: nccl
dist_url: env://
logger_freq: 50
num_workers: 8
output_dir: .
pretrained: checkpoint.pth
val_freq: 1
