arch: resnet50
batch_size: 512
blur_prob: 0.5
crop_scale:
- 0.2
- 1.0
crop_size: 224
dataset: ImageNet
dim: 2048
epochs: 100
fix_pred_lr: true
hflip_prob: 0.5
lr: 0.05
momentum: 0.9
pred_dim: 512
weight_decay: 0.0001
# MSAT parameters
start_val: 0.3
end_val: null
# Misc parameters
data_path: null
output_dir: null
