arch: resnet50
patch_size: 16
drop_path_rate: 0.1
batch_size: 2048
blur_prob: 0.5
crop_scale:
- 0.2
- 1.0
crop_size: 224
dataset: ImageNet
dim: 2048
epochs: 300
fix_pred_lr: true
hflip_prob: 0.5
lr: 0.0
momentum: 0.9
pred_dim: 512
weight_decay: 1e-6
# MinSim parameters
select_fn: identity
num_crops: 2
# Misc parameters
data_path: null
output_dir: null
lambd: 0.0051
projector: 8192-8192-8192
learning_rate_weights: 0.2
learning_rate_biases: 0.0048
grad_accum_steps: 1
use_adv_metric: true
adv_metric_freq: 10
logger_freq: 50