arch: vit_tiny
avgpool: false
batch_size: 256
ckp_key: teacher
crop_size: 32
dataset: ImageNet
epochs: 100
img_size: 32
lars: false
lr: 0.001
momentum: 0.9
n_last_blocks: 4
patch_size: 4
pretrained: checkpoint.pth
resize_size: 36
weight_decay: 0.0