batch_size: 256
ckp_key: model
crop_size: 32
dataset: CIFAR10
epochs: 100
lars: false
lr: 30.0
momentum: 0.9
pretrained: checkpoint.pth
resize_size: 36
weight_decay: 0.0
# Misc
dist_url: env://
dist_backend: nccl
num_workers: 8
val_freq: 1
logger_freq: 50