arch: resnet18
batch_size: 512
blur_prob: 0.0
crop_scale: !!python/tuple
- 0.2
- 1.0
crop_size: 32
dataset: CIFAR10
dim: 2048
epochs: 800
fix_pred_lr: true
hflip_prob: 0.5
lr: 0.06
momentum: 0.9
pred_dim: 512
weight_decay: 0.0005
