arch: resnet18
batch_size: 512
blur_prob: 0.0
crop_scale:
- 0.2
- 1.0
crop_size: 32
dataset: CIFAR10
dim: 2048
epochs: 800
fix_pred_lr: true
hflip_prob: 0.5
lr: 0.06
momentum: 0.9
pred_dim: 512
weight_decay: 0.0005
# MinSim parameters
select_fn: identity
num_crops: 2
use_intermitting_training: false
hvp_step: 1
scale_factor_select: 1.0
# Misc parameters
data_path: null
output_dir: null
optimizer: sgd
clip_grad: 0.0